title: FOSS Foundations Directory
description: Comprehensive metadata directory about non-profit FOSS Foundations.
theme: just-the-docs

url: https://fossfoundation.info

author: Shane Curcuru
twitter:
  username: shanecurcuru
  card: summary

# Just-the-docs configuration
search_enabled: true
heading_anchors: true
