title: FOSS Foundations Directory
description: Comprehensive metadata directory about non-profit FOSS Foundations.
theme: just-the-docs
url: https://fossfoundation.info
ga_tracking: G-LF1HV9CP39

author: Shane Curcuru
twitter:
  username: shanecurcuru
  card: summary

# Just-the-docs configuration
search_enabled: true
heading_anchors: true
gh_edit_link: true

nav_external_links:
  - title: Choose A Foundation
    url: https://chooseafoundation.com/
  - title: FOSS Foundation Funding
    url: https://fossfunding.com/
  - title: Shane Curcuru / Punderthings
    url: https://punderthings.com/

# Jekyll setup and collections
collections:
  foundations:
    output: true
    sort_by: name
    permalink: /:collection/:path

# Defaults
defaults:
  - 
    scope:
      path: ""
      type: "foundations"
    values:
      layout: foundation
