title: FOSS Foundations Directory
description: Comprehensive metadata directory about non-profit FOSS Foundations.
theme: just-the-docs
url: https://fossfoundation.info
ga_tracking: 

author: Shane Curcuru
twitter:
  username: shanecurcuru
  card: summary

# Just-the-docs configuration
search_enabled: true
heading_anchors: true
gh_edit_link: true

nav_external_links:
  - title: Choose A Foundation
    url: https://chooseafoundation.com/
  - title: FOSS Foundation Funding
    url: https://fossfunding.com/
